# Generated by Django 3.2.6 on 2021-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('number_of_employee', models.IntegerField()),
                ('naics', models.IntegerField()),
                ('corporation_id', models.IntegerField()),
            ],
        ),
    ]
